### ISSUE TITLE
[Help] 🤔 Hugging Face 自动更新

### ISSUE THREAD

**Issue by Aoan2011** [Harry-zklcdc/go-proxy-bingai#142]
### Describe the help wanted

我应该如何将部署在 hugging face 上的项目更新到最新版呢？
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/136089405/352b655f-94d9-4d76-b0ab-0d09428d8b36)

### Steps to behave

打开项目，点击设置图标，点击关于

### Expected behavior

自动更新到最新版本

### Screenshots

部署日志：
===== Build Queued at 2023-08-16 09:43:07 / Commit SHA: b0c4207 =====

--> FROM docker.io/library/golang:alpine@sha256:445f34008a77b0b98bf1821bf7ef5e37bb63cc42d22ee7c21cc17041070d134f
DONE 0.0s

--> FROM docker.io/library/alpine@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
DONE 0.0s

--> RUN apk --no-cache add git
CACHED

--> WORKDIR /workspace/app
CACHED

--> RUN git clone https://github.com/Harry-zklcdc/go-proxy-bingai.git /workspace/app
CACHED

--> RUN go build -ldflags="-s -w" -tags netgo -trimpath -o go-proxy-bingai main.go
CACHED

--> WORKDIR /workspace/app
CACHED

--> COPY --from=builder /workspace/app/go-proxy-bingai .
CACHED

--> Pushing image
DONE 0.4s

--> Exporting cache
DONE 0.2s

### Versions

- OS: macOS Monterey 12
- Browser & Version: Microsoft Edge 115
- GoProxiBing Version: v1.11.4

**Comment by luckyEason** [comment]
重新部署




一级p
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Harry-zklcdc/go-proxy-bingai"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月16日(星期三) 晚上8:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Harry-zklcdc/go-proxy-bingai] [Help] 🤔 Hugging Face 自动更新 (Issue #142)





 
Describe the help wanted
 
我应该如何将部署在 hugging face 上的项目更新到最新版呢？
 
 
Steps to behave
 
打开项目，点击设置图标，点击关于
 
Expected behavior
 
自动更新到最新版本
 
Screenshots
 
部署日志：
 ===== Build Queued at 2023-08-16 09:43:07 / Commit SHA: b0c4207 =====
 
--&gt; FROM ***@***.***:445f34008a77b0b98bf1821bf7ef5e37bb63cc42d22ee7c21cc17041070d134f
 DONE 0.0s
 
--&gt; FROM ***@***.***:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
 DONE 0.0s
 
--&gt; RUN apk --no-cache add git
 CACHED
 
--&gt; WORKDIR /workspace/app
 CACHED
 
--&gt; RUN git clone https://github.com/Harry-zklcdc/go-proxy-bingai.git /workspace/app
 CACHED
 
--&gt; RUN go build -ldflags="-s -w" -tags netgo -trimpath -o go-proxy-bingai main.go
 CACHED
 
--&gt; WORKDIR /workspace/app
 CACHED
 
--&gt; COPY --from=builder /workspace/app/go-proxy-bingai .
 CACHED
 
--&gt; Pushing image
 DONE 0.4s
 
--&gt; Exporting cache
 DONE 0.2s
 
Versions
  
OS: macOS Monterey 12
 
Browser &amp; Version: Microsoft Edge 115
 
GoProxiBing Version: v1.11.4
  
Additional context
 
No response

**Comment by Aoan2011** [comment]
就不能自动更新吗？

**Comment by Aoan2011** [comment]
还是 1.11.4 ?

**Comment by Aoan2011** [comment]
是要 factory reboot？

**Comment by qinguoluo** [comment]
我的是部署在vercel上的，先把作者的项目fork到自己的仓库，如果作者更新了，我就同步我的仓库，然后vercel上的会自动同步更新部署。我只需要在浏览器上刷新一下，版本就更新到最新了。自动更新估计不行吧？我这顶多算半自动更新。

**Comment by luckyEason** [comment]
> 我的是部署在vercel上的，先把作者的项目fork到自己的仓库，如果作者更新了，我就同步我的仓库，然后vercel上的会自动同步更新部署。我只需要在浏览器上刷新一下，版本就更新到最新了。自动更新估计不行吧？我这顶多算半自动更新。

vercel其实是可以的，wiki里有

**Comment by qinguoluo** [comment]
> > 我的是部署在vercel上的，先把作者的项目fork到自己的仓库，如果作者更新了，我就同步我的仓库，然后vercel上的会自动同步更新部署。我只需要在浏览器上刷新一下，版本就更新到最新了。自动更新估计不行吧？我这顶多算半自动更新。
> 
> vercel其实是可以的，wiki里有

我没有找到。不过对于我们这种小白来说，现在这样也可以了，再复杂点咱也搞不懂。

**Comment by qinguoluo** [comment]
> > 我的是部署在vercel上的，先把作者的项目fork到自己的仓库，如果作者更新了，我就同步我的仓库，然后vercel上的会自动同步更新部署。我只需要在浏览器上刷新一下，版本就更新到最新了。自动更新估计不行吧？我这顶多算半自动更新。
> 
> vercel其实是可以的，wiki里有

我没有找到。不过对于我们这种小白来说，现在这样也可以了，再复杂点咱也搞不懂。

**Comment by luckyEason** [comment]
> > > 我的是部署在vercel上的，先把作者的项目fork到自己的仓库，如果作者更新了，我就同步我的仓库，然后vercel上的会自动同步更新部署。我只需要在浏览器上刷新一下，版本就更新到最新了。自动更新估计不行吧？我这顶多算半自动更新。
> 
> > 
> 
> > vercel其实是可以的，wiki里有
> 
> 
> 
> 我没有找到。不过对于我们这种小白来说，现在这样也可以了，再复杂点咱也搞不懂。

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/109937362/01010807-18ed-4aeb-98cf-35ab033a8ac5)

**Comment by WaiterGin** [comment]
factory reboot以后多刷新几次页面就好了

**Comment by sugar1688** [comment]
> 我的是部署在vercel上的，先把作者的项目fork到自己的仓库，如果作者更新了，我就同步我的仓库，然后vercel上的会自动同步更新部署。我只需要在浏览器上刷新一下，版本就更新到最新了。自动更新估计不行吧？我这顶多算半自动更新。

怎么同步到个人仓库，重新FORK一下吗？

**Comment by qinguoluo** [comment]
> > 我的是部署在vercel上的，先把作者的项目fork到自己的仓库，如果作者更新了，我就同步我的仓库，然后vercel上的会自动同步更新部署。我只需要在浏览器上刷新一下，版本就更新到最新了。自动更新估计不行吧？我这顶多算半自动更新。
> 
> 怎么同步到个人仓库，重新FORK一下吗？

fork之后你就会在你个人的仓库中看到go-proxy-bingai这个项目了。打开你的项目，如果作者已经更新，你会看到提示的。
